services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/noteapp?authSource=admin
      MONGODB_DB_NAME: noteapp
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-secret-key-here}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      DEBUG: "True"
      ENVIRONMENT: development
      LOG_LEVEL: INFO
      RATE_LIMIT_PER_MINUTE: '{"default":100,"auth":20,"user":200}'
      SESSION_EXPIRE_MINUTES: 60
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      API_V1_STR: /api/v1
      CORS_ORIGINS: '["http://localhost:3000"]'
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend/src:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./infrastructure/mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: noteapp
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 