apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values - replace with actual secure values
  MONGODB_URI: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQGhvc3Q6MjcwMTcvZGF0YWJhc2U=
  POSTGRES_USER: dXNlcm5hbWU=
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3JkXzEyMw==
  POSTGRES_DB: bm90ZWFwcA==
  JWT_SECRET_KEY: c2VjdXJlX2p3dF9zZWNyZXRfa2V5XzMyX2NoYXJhY3RlcnM= 