apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
  labels:
    app: noteapp
    component: auth
    environment: production
  annotations:
    description: "JWT secret key for NoteApp authentication"
    lastUpdated: "2025-04-27"
    createdBy: "security-team"
    rotationSchedule: "monthly"
type: Opaque
data:
  # These are example values - in production, use your own secure generated values
  jwt_secret_key: TXlTdXBlclNlY3VyZUpXVFNlY3JldEtleTEyMyMkJV4mKigpXysjQEAhIQ== # 256-bit secure random string
  jwt_algorithm: SFMyNTY= # HS256
  access_token_expire_minutes: MzA= # 30 