[tool.pylint]
max-line-length = 120
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
    "R0903",  # too-few-public-methods
    "W0511",  # fixme
]
good-names = ["i", "j", "k", "ex", "Run", "_", "id", "db"]
ignore = ["CVS", ".git", ".env", "__pycache__", "venv", ".venv"]
ignore-patterns = ["^\\.#"]

[tool.pylint.format]
indent-after-paren = 4

[tool.pylint.basic]
good-names-rgxs = "^[_a-z][_a-z0-9]?$"

[tool.pylint.design]
max-args = 8
max-attributes = 10
max-bool-expr = 5
max-branches = 15
max-locals = 20
max-parents = 7
max-public-methods = 25
max-returns = 8
max-statements = 50
min-public-methods = 1

[tool.pylint.similarities]
ignore-comments = true
ignore-docstrings = true
ignore-imports = true
min-similarity-lines = 6

[tool.pylint.typecheck]
ignored-modules = ["pydantic"]
generated-members = ["objects.*"]

[tool.pylint.messages_control]
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
    "R0903",  # too-few-public-methods
    "W0511",  # fixme
] 