apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2 # Start with 2 replicas
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: backend-db-volume
          emptyDir: {} # Hoặc persistentVolumeClaim nếu cần lưu trữ lâu dài
      containers:
      - name: backend
        image: your-docker-registry/noteapp-backend:latest # Image sẽ được cập nhật bởi Jenkins
        ports:
        - containerPort: 8000
        env:
          # MongoDB Connection URI từ secret
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: uri

          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets # Name of the K8s secret for app
                key: jwt-secret      # Key within the secret
          - name: ACCESS_TOKEN_EXPIRE_MINUTES # Keep this or move to ConfigMap
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: access-token-expire
          - name: ENVIRONMENT # Keep this or move to ConfigMap
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: environment
          - name: DEBUG # Keep this or move to ConfigMap
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: debug
        volumeMounts:
          - name: backend-db-volume
            mountPath: /app/data # Gắn volume vào thư mục chứa DB
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000 # Match user ID in Dockerfile
          allowPrivilegeEscalation: false
          # readOnlyRootFilesystem: false # Cannot be true due to SQLite writing to /app/data
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 