apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # This name is used in the MONGODB_URI
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb # Selects pods with label app=mongodb
  ports:
    - protocol: TCP
      port: 27017        # Port exposed by the service
      targetPort: 27017  # Port on the pod container
  type: ClusterIP # Only accessible within the cluster 