apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: default
  labels:
    app: noteapp
    component: database
    environment: production
  annotations:
    description: "MongoDB credentials for NoteApp database"
    lastUpdated: "2025-04-27"
    createdBy: "security-team"
    rotationSchedule: "quarterly"
type: Opaque
data:
  # These are example values - in production, use your own secure generated values
  username: bm90ZWFwcF9hZG1pbg== # noteapp_admin
  password: TXlTdXBlclNlY3VyZVBhc3N3b3JkMTIzISM= # MySecurePassword123!#
  database: bm90ZWFwcF9wcm9k # noteapp_prod
  uri: bW9uZ29kYjovL25vdGVhcHBfYWRtaW46TXlTdXBlclNlY3VyZVBhc3N3b3JkMTIzISNAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3L25vdGVhcHBfcHJvZD9hdXRoU291cmNlPWFkbWlu # Full connection string with new credentials 