apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
  labels:
    app: noteapp
    component: database
    environment: production
  annotations:
    description: "PostgreSQL credentials for NoteApp database"
    lastUpdated: "2025-04-27"
    createdBy: "security-team"
    rotationSchedule: "quarterly"
type: Opaque
data:
  # These are example values - in production, use your own secure generated values
  username: bm90ZWFwcF91c2Vy # noteapp_user
  password: UG9zdGdyZXNTZWN1cmVQYXNzMTIzISM= # PostgresSecurePass123!#
  database: bm90ZWFwcF9wcm9k # noteapp_prod
  host: cG9zdGdyZXMtc2VydmljZQ== # postgres-service
  port: NTQzMg== # 5432
  uri: cG9zdGdyZXNxbDovL25vdGVhcHBfdXNlcjpQb3N0Z3Jlc1NlY3VyZVBhc3MxMjMhI0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvbm90ZWFwcF9wcm9k # Full connection string 