repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-private-key
    -   id: check-merge-conflict

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-docstrings",
            "flake8-simplify",
        ]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.3.0
    hooks:
    -   id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@9.3.0
        -   eslint-plugin-react@7.34.0
        -   eslint-config-standard@17.1.0
        -   "@typescript-eslint/eslint-plugin@7.2.0"
        -   "@typescript-eslint/parser@7.2.0" 